### ISSUE TITLE
[Problem] only italics in Safari (iOS/macOS)

### ISSUE THREAD

**Issue by tobysommer** [philipbelesky/inter-ui#2] opened 2018-12-07 05:45 UTC
Hi

and first of all, thanks for this package! I'm using it in several web applications with webpack.

Therefore I use the `@import "~inter-ui";` statement to import the the CSS + Fonts into my project. This works in all browsers (even IE11), but not in Safari (tested on macOS Mojave and iOS 12.*) - Here I only get an all italic font  :(

I tried to load the _web hinted_-version via `@import "~inter-ui/inter-ui-hinted.css";` but this fails with the following error:

```
Module not found: Error: Can't resolve './Inter UI (web hinted)/Inter-UI.var.woff2' in '/Users/tobias/Code/eis/node_modules/inter-ui'
```

I then copied the _web hinted_ files manually and it seems to work...

I wonder why
a) all Safaris only show an italic font when using `@import "~inter-ui";` 
b) how to (correctly) use the _web hinted_-version
c) what the difference between _web_ and _web hinted_ is

Thanks in advance!

**Comment by philipbelesky** [comment] 2018-12-09 10:19
a - Sorry what is the "`~`" tilde doing in the import path? If its an alias to a home folder, shouldn't it be "`~/`". The other option is could you try importing from a relative path? 
b - When you say you copied the web hinted files, where did copy them to? I've had some problems with figuring out npm deals with paths, but I can't recall the specifics. Not sure if this is specifically related to this repo though.
c - The main inter ui repo I think explains the distinction somewhere. I *think* the different is the web hinted version better ensures the font outlines match up with pixel boundaries.

**Comment by tobysommer** [comment] 2018-12-09 21:55
Hi and thanks for your feedback.

To explain my use case a little more: I'm using the Laravel PHP Framework which comes with _Laravel Mix_ which provides a fluent API for defining Webpack build steps for a Laravel application.

I use Yarn for package managing and running the NPM build scripts; therefore I added the font first via `yarn add --dev inter-ui`. So my `package.json` includes the font:

```
{
    "private": true,
    "scripts": {
        "bla": "some scripts..."
    },
    "devDependencies": {
        "someOtherDependencies": "^1.1.1",
        "inter-ui": "^3.0.0",
    }
}
```

To answer your questions:

a - the tilde is not an alias to my home directory; it points to the `node_modules` directory inside the application. So it's a shortcut: Instead of writing `@import "../../node_modules/inter-ui";` I just use `@import "~inter-ui";` which is the same. Also `@import "../../node_modules/inter-ui/inter-ui.css";` is the same: It doesn't work in Safari (_"doesn't work"_ means that I only get an italic default font...). So using the relative path doesn't solve the problem.

b - because of Webpack, all files from the `node_modules/inter-ui/Inter UI (web)/*` files are copied to my public directory in `public/fonts/vendor/inter-ui/Inter UI (web)/`. If I then manually copy the `node_modules/inter-ui/Inter UI (web hinted)` directory to `public/fonts/vendor/inter-ui/Inter UI (web hinted)` and then replace all occurrences of `/fonts/vendor/inter-ui/Inter UI (web)/` with `/fonts/vendor/inter-ui/Inter UI (web hinted)/` in the `public/css/app.css` file, It also works in Safari...

I can't unfortunately use `@import "../../node_modules/inter-ui/inter-ui-hinted.css";` because Webpack/NPM is complains about missing font files within the `/Inter UI (web hinted)` directory which are referenced in the `inter-ui-hinted.css` file ...


Thanks in advance and have a nice day :)

**Comment by philipbelesky** [comment] 2018-12-10 08:36
Ok, I think I understand your issue but I'm not sure how to go about resolving it. In my case I essentially duplicate the CSS files contained in this repo so I can call them directly from SASS and use a full relative path import when using webpack. Alternately I copy the files over to a `/static/` directly as part of the packing process so the css can import them outside of `node_modules`.

I'm not sure what the proper convention here, and somewhat cautious about changing how things work currently given altering the existing path setup would presumably be a breaking change for people who currently rely on. Is there a path change that you can verify would solve this issue? Otherwise I'm not sure what I can do.

For your particular issue maybe one of the setups I mention above might work, or using a file loader package, [such as described here?](https://www.chriscourses.com/blog/loading-fonts-webpack)

**Comment by philipbelesky** [comment] 2018-12-10 08:43
Ok, in updating this repo to track the main repo's latest release (3.1) it turns out there was a regression (in 3.0) that meant italic support in Safari needed an alternate import method. If you update this repo to the latest version then check out the bottom of the CSS files I've copied over the comments that explain the workaround.

**Comment by tobysommer** [comment] 2018-12-10 13:36
Thanks @philipbelesky YMMD! It just works (tm) 👍 

I use the `@import "~inter-ui";` statement and just updated my font stack to include `'Inter UI var alt'` and it now works in all browsers. Great!

Thanks again and have nice day :D

**Comment by tobysommer** [comment] 2018-12-10 14:05
Hmmm... it works in Safari MAC, but not on iOS though....

**Comment by jbach** [comment] 2018-12-11 13:58
See https://github.com/rsms/inter/issues/79

**Closed** 2018-12-12 20:36 UTC
Labels: bug
